type Query {
  hello: String

  me: UserResult!

  questions: [Question!]
  question(id: ID!): Question

  answers: [Answer!]
  answer(id: ID!): Answer
}

type Mutation {
  signup(input: AuthInput!): AuthResult!
  signin(input: AuthInput!): AuthResult!

  questionCreate(input: QuestionInput!): QuestionResult!
  questionUpdate(id: ID!, input: QuestionInput!): QuestionResult!
  questionDelete(id: ID!): QuestionResult!

  answerCreate(input: AnswerInput!): AnswerResult!
  answerUpdate(id: ID!, input: AnswerInput!): AnswerResult!
  answerDelete(id: ID!): AnswerResult!
}

type User {
  id: ID!
  username: String!

  questions: [Question!]!
  answers: [Answer!]!
}

type UserResult {
  error: String
  user: User
}

input AuthInput {
  username: String!
  password: String!
}

type AuthResult {
  error: String
  token: String
}

type Question {
  id: ID!
  title: String!
  content: String!
  tags: String!
  user: User!
  answers: [Answer!]!
}

input QuestionInput {
  title: String!
  content: String!
  tags: String!
}

type QuestionResult {
  error: String
  question: Question
}

type Answer {
  id: ID!
  content: String!
  question: Question!
  user: User!
}

input AnswerInput {
  content: String!
  questionId: ID!
}

type AnswerResult {
  error: String
  answer: Answer
}
