type Query {
  hello: String
  questions: [Question!]
  question(id: ID!): Question
}

type Mutation {
  signup(input: AuthInput!): AuthResult!
  signin(input: AuthInput!): AuthResult!

  questionCreate(input: QuestionInput!): QuestionResult!
  questionUpdate(id: ID!, input: QuestionInput!): QuestionResult!
  questionDelete(id: ID!): QuestionResult!
}

type User {
  id: ID!
  username: String!
}

input AuthInput {
  username: String!
  password: String!
}

type AuthResult {
  error: String
  token: String
}

type Question {
  id: ID!
  title: String!
  content: String!
  tags: String!
}

input QuestionInput {
  title: String!
  content: String!
  tags: String!
}

type QuestionResult {
  error: String
  question: Question
}
